matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
      osx_image: xcode10

env: 
  - RELEASE_FILES=$TRAVIS_BUILD_DIR/target/*.zip

before_install:
  - export TRAVIS_TAG=`mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec`
  - echo $TRAVIS_TAG
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      mkdir $TRAVIS_BUILD_DIR/dist && chmod a+w $TRAVIS_BUILD_DIR/dist
      docker build -t android-openssl .
      docker run -it -d --user build --name openssl-container -v $TRAVIS_BUILD_DIR/dist:/home/build/app/dist -e TRAVIS_TAG=$TRAVIS_TAG android-openssl bash
    fi
  
script:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      docker exec --user build openssl-container bash /home/build/app/build-android.sh $TRAVIS_TAG
    else
      bash ./build-ios.sh $TRAVIS_TAG
    fi
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      mvn package -P android
    else
      mvn package -P ios
    fi
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export TRAVIS_TAG=$TRAVIS_TAG-Android
    else
      export TRAVIS_TAG=$TRAVIS_TAG-iOS
    fi

before_deploy:
  - git config --local user.name "cwack"
  - git config --local user.email "christian.wack@letsdev.de"
  - echo "List release files"
  - ls $RELEASE_FILES

deploy:
  provider: releases
  api_key:
    secure: "PmwAd6negPriiyj1BbnMVogFiXKkPn05dSaV/G5y+unqB60OgtKu3JPU2f1qCPHocjmvniOGJ8M8Lvqw19DWNUJ47NDlr/RMDzihZeQHPKt9kAkk8EvwiE/4FM7g4f2GcT/kuwanRsymaZkPiJYe847hZrOXP+ba/8VfLv6OtVK85Tnny8+hHe7GCQag7taOJCIFUosnHo70kXXwhbArsx8V6rDbbwlrmzpktjCMdJTue2uPs4xXGThM4AJC3hRSmbxN977QlHMr2+OW2NL7ofwUbwRA6mj8b0I6FZy6JpUYjfh9hLTiv5z032NLUm21SwQy7grQMJAzoBplQWBGerLZfJvcOrSmGTkC8poiKngIFQ4fR6lo8Pg/c6FE00FvekVEuiX5u5kPzzkPFnu7wFXiX2XT23bbCKKdqLciBea8ReTjINRlFBUspWHXe5wW4ONUr7bVBggfYF989PFBBLuF7XYwJki4P08CIEqeA/nOfqNqsGnA6kDOpvcaOl8zUclnlCVk0D5dJwsFaeckzxOYV98FDMe40bcNBUOsX7LQ2N82/o3QM/zkC+f39haM2ExvjJSuP7vjPWldrMNLquPHzSoOuK5q1oX+MIkxMqOLFSr4zWdrayINCB5vZ3sg04c9bNZXGhNdVLNiDkFC52b6AGoV9maLoI/BUqyUlII="
  file_glob: true
  tag_name: $TRAVIS_TAG
  file: $RELEASE_FILES
  name: Release-$TRAVIS_TAG
  skip_cleanup: true
  on:
    branch: master